### ISSUE TITLE
How to use conptyshell

### ISSUE THREAD

**Issue by DannyBrock123** [t3l3machus/Villain#109]
WHat is conptyshell do and how do I use it? Please give examples and please give me on how to use it. Thanks!

**Comment by t3l3machus** [comment]
Hi, the command `conptyshell` executes [Invoke-ConPtyShell.ps1](https://github.com/antonioCoco/ConPtyShell/blob/master/Invoke-ConPtyShell.ps1) against an already established powershell session (fully functional shell starting as a new process). Please, check how to use it [here](https://github.com/t3l3machus/Villain/blob/main/Usage_Guide.md#The-conptyshell-Command). Also, I demonstrated it in this [video](https://www.youtube.com/watch?v=HR1KM8wrSV8) (5:40).
