### ISSUE TITLE
Available templates

### ISSUE THREAD

**Issue by User-790** [t3l3machus/Villain#110]
Is there a list of templates that are available we can refer to? I have tried to use a few formats from msfvenom and none have worked so far.

**Comment by t3l3machus** [comment]
You could do something like `tree path/to/Villain/Core/payload_templates`.  
![image](https://github.com/t3l3machus/Villain/assets/75489922/930bd8c5-3e7d-40a1-bcb8-f6117284dfc1)
  
 Also, you can use tab auto-complete while generating to see your options (type `generate payload=windows/netcat/` and hit tab-tab). What exactly did you try with msfvenom and it didn't work?

**Comment by User-790** [comment]
Alright, thank you for your help! Helps a lot
