### ISSUE TITLE
Is there a way to port foward Villain? 

### ISSUE THREAD

**Issue by DannyBrock123** [t3l3machus/Villain#111]
I'm trying to port foward Villain so I can connect to other computers on my network, how do I do it? I tried using Ngrok but it just says incorrect IP

**Comment by 0067sdsm** [comment]
Try your routers config page.

**Comment by Cr7pt0nic** [comment]
Instead of using your router configuration which would expose your public facing IP Address I highly recommend using a VPN, than using ngrok and port forwarding the local villain port (example: 4443) and than modify the powershell payload to include the ngrok host and ngrok tunneling port instead.
