### ISSUE TITLE
Issues with connecting

### ISSUE THREAD

**Issue by Burgercraft** [t3l3machus/Villain#114]
I just started using your program, but i can't connect with my "Victim-maschine" (my own computer) do you have any suggestions on what could have gone wrong? Disclaimer: I use kali linux, Antivirus was off, I started powershell as Admin, I used eth0 as lhost. I followed like every new tutorial and couldn't find the issue. Do I have to have another programm open? sry for my bad english.

**Comment by t3l3machus** [comment]
You don't need another program. There must be some network related issue. If you are using a kali VM make sure the network adapter settings allow your machine to communicate with the host like separate machines. If it's not that, google the error message you get when running the payload and you will probably be able to resolve the issue.

**Comment by Burgercraft** [comment]
Thx for the response i didn't expect to hear from you. The thing with the adapter in VM worked, thx.
