### ISSUE TITLE
Ignoring unsupported arguments: OBFUSCATE

### ISSUE THREAD

**Issue by AdMediastic** [t3l3machus/Villain#118]
This is the error I am getting! 
![image](https://github.com/t3l3machus/Villain/assets/121597815/203ee41d-e8c5-4931-8705-b79906550094)

**Comment by t3l3machus** [comment]
@AdMediastic 
Functions like "obfuscate" and "encode" are enabled for each payload from the "attrs" dictionary in each template. So, to enable the obfuscate function for this particular payload you need to edit `Villain/Core/payload_templates/windows/netcat/powershell_reverse_tcp.py` and append `'obfuscate' : True` to it.
![image](https://github.com/t3l3machus/Villain/assets/75489922/e83d5e43-5923-498b-b2e5-cf3893c51418)


The reason it is disabled by default in certain payload templates is that, the obfuscate class does not work perfectly with non-hoaxshell payloads and I didn't have the time to adjust it yet, but you can experiment with it if you like.
