### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by philxdes** [t3l3machus/Villain#122]
When I run the netcat payload on another pc it just doesn’t send anything back (not even some sort of error or message saying connected) to my console on Linux, I believe I’m doing everything right, and it’s not an antivirus issue because I disabled that on my windows.  Any ideas?

**Comment by t3l3machus** [comment]
Try connecting back to a simple netcat listener. If that works, there is no reason why it should fail with Villain. It most likely is a network issue, the host you are trying to connect back to the attacker from can't reach you server.

**Comment by philxdes** [comment]
could it have anything to do with my linux os being on a vm?

**Comment by philxdes** [comment]
the netcat listener is working just fine, so im not exactly sure what the issue is unless it is something to do with my vm
