### ISSUE TITLE
[Feature request] incorporate payload to steganography

### ISSUE THREAD

**Issue by Takaeda4413** [t3l3machus/Villain#125]
Hi, I am trying to incorporate the made powershell script into an image so that it can become a steganography image wherein an unwanted user opens the image and the script automatically executes itself. Although im having problems when incorporating the script.
Any tips on how to accomplish this? 
Thanks!

**Comment by t3l3machus** [comment]
Hi @Takaeda4413, really sorry for the delay. 

That's a complex task, and I'm short on time, so I can't elaborate right now. 
Something different but not far from what you're trying to achieve that might come in handy -> https://medium.com/@sam.rothlisberger/embed-a-malicious-executable-in-a-normal-pdf-or-exe-81ee5339707e
