### ISSUE TITLE
netifaces error

### ISSUE THREAD

**Issue by hector-0ni** [t3l3machus/Villain#126]
**I gave ./Villain.py executable permissions but when trying to run it receive this error:**

Traceback (most recent call last):
  File "/home/phantom/Villain/./Villain.py", line 11, in <module>
    from Core.common import *
  File "/home/phantom/Villain/Core/common.py", line 10, in <module>
    import netifaces as ni
ModuleNotFoundError: No module named 'netifaces'

Dual booting Parrot OS

**Comment by t3l3machus** [comment]
Hey, you need to install the requirements:  
```pip3 install -r requirements.txt```  
You should also install gnome-terminal (required for one of the framework's commands):  
```sudo apt update&&sudo apt install gnome-terminal```
