### ISSUE TITLE
A BUG, a suggestion

### ISSUE THREAD

**Issue by bobmaifz1** [t3l3machus/Villain#127]
1. After the session is established, the connection will be disconnected after a period of time. I used powershell to establish a netcat connection.
2. I didn’t see the file download function. I think this function is necessary.

**Comment by t3l3machus** [comment]
Hi, the period a session will stay alive for depends on many factors and conditions (e.g., which command was used to establish the session, the OS version of the target, the anti-malware functions running on the target, etc). I've had sessions run for days with no issues as well as sessions that would die shortly.

The download will be added in the next update along with other improvements and bug fixes. I can'y say when it will be ready right now.

Thanks for using Villain :)
