### ISSUE TITLE
ModuleNotFoundError when trying to run Villain.py

### ISSUE THREAD

**Issue by Moondog85** [t3l3machus/Villain#130]
└─# python3 Villain.py
Traceback (most recent call last):
  File "/home/term1/villain/Villain.py", line 11, in <module>
    from Core.common import *
  File "/home/term1/villain/Core/common.py", line 15, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by t3l3machus** [comment]
Hi, if you are on kali, you can install villain by running `sudo apt install villain` and then just run `villain` to start it. If you want to use the repo, you must install the requirements first (there's an installation & usage section in the main README).
