### ISSUE TITLE
Help me with nohup = "nohup.out" :( 

### ISSUE THREAD

**Issue by Enchance627** [t3l3machus/Villain#132]
Hello, I am using villain from a virtual machine that uses kali linux, the main system is Ubuntu. I have created a code for Linux, and when I try to use it in Ubuntu it does not work, it tells me something about nohup input and output "nohup.out" and I do not log in to villain. Could someone help me solve it please?

**Comment by t3l3machus** [comment]
@Enchance627 try deleting nohup from the command before you run it.

**Comment by Enchance627** [comment]
I tried as you told me and it says "bash: line 1: curl: order not found :(

**Comment by Enchance627** [comment]
What can i trie

**Comment by Enchance627** [comment]
> @Enchance627 try deleting nohup from the command before you run it.

I tried as you told me and it says "bash: line 1: curl: order not found

**Comment by Enchance627** [comment]
I tried as you told me and it says "bash: line 1: curl: order not found

**Comment by t3l3machus** [comment]
Please paste screenshot of the payload you are running and the error message

**Comment by Enchance627** [comment]
![h](https://github.com/t3l3machus/Villain/assets/152353231/861e0c2d-8e46-439d-b90f-e8bae5f35e01)

**Comment by t3l3machus** [comment]
@Enchance627 looks like curl is not installed on the system. run `sudo apt install curl` and try again

**Comment by Enchance627** [comment]
I dont have sudo su
