### ISSUE TITLE
Python library error

### ISSUE THREAD

**Issue by calex80** [t3l3machus/Villain#135]
I need help to solve this Python issue, which basically refers to ```UnboundLocalError: cannot access local variable 'raw_data' where it is not associated with a value``` 

Any help?

![image](https://github.com/t3l3machus/Villain/assets/58860205/3e6b05ff-d4dc-45b9-be2c-97be986dea51)

**Comment by t3l3machus** [comment]
Hi, try commenting out line 1749 in villain_core.py

**Comment by calex80** [comment]
I did it and the error is gone! but now I am receiving this another failure ```[Warning] failed to process a request. ```

![image](https://github.com/t3l3machus/Villain/assets/58860205/28ef651a-ae83-491c-8fe4-0cd69ba93e3c)

**Comment by calex80** [comment]
Thank you! it's working! so appretiated ;)

**Comment by t3l3machus** [comment]
if the error comes up, post it here so I can see what was the deal, thanks
