### ISSUE TITLE
Using villain with Local tunnel or ngrok

### ISSUE THREAD

**Issue by HussHemAG** [t3l3machus/Villain#136]
Hello, I was looking at hoaxshell and its ability to use ngrok and Local Tunnel.
I was wondering if something similar is possible in Villain

**Comment by t3l3machus** [comment]
Hi, Villain does not have built in support for ngrok / LT as hoaxshell used to. It is possible to make it work with ngrok, probably it requires minor modifications in payloads. The feature of automatically using ngrok or LT in hoaxshell was someone's commit, it used to work at the time, not sure what is the status of it now.
Check this out, might work -> https://github.com/t3l3machus/Villain/issues/17
