### ISSUE TITLE
help dns?

### ISSUE THREAD

**Issue by NyxKazuya** [t3l3machus/Villain#138]
can dns be used?

**Comment by t3l3machus** [comment]
If you edit Villain/Core/settings.py and set the following to False:
![image](https://github.com/t3l3machus/Villain/assets/75489922/93002370-18da-40f4-b42b-718ba87da916)

You will be able to provide domains instead of IPs for LHOST. Hope that solves your issue, not sure what you meant exactly.

**Comment by NyxKazuya** [comment]
> Si edita Villain/Core/settings.py y establece lo siguiente en False: ![imagen](https://private-user-images.githubusercontent.com/75489922/294748628-93002370-18da-40f4-b42b-718ba87da916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDA0MzcsIm5iZiI6MTcwNDY0MDEzNywicGF0aCI6Ii83NTQ4OTkyMi8yOTQ3NDg2MjgtOTMwMDIzNzAtMThkYS00MGY0LWI0MmItNzE4YmE4N2RhOTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE1MDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhODFjNjExMjMwZDFhYzE3YWYzODA0OGY2MTE2MDQzOGNiNTMwZTJmYzgwNTJhMTgyOTBhMTNkZTc4NDYzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jBdOq7dBLQshajb4bC9n6xRb_V_KazpSYs2289hLed8)
> 
> Podrá proporcionar dominios en lugar de IP para LHOST. Espero que eso resuelva tu problema, no estoy seguro de lo que quisiste decir exactamente.

Hello, thank you very much for your quick response.
 I wanted to know if I can use a dynamic DNS instead of my IP address

**Comment by t3l3machus** [comment]
The validate_lhost_as_ip config is now deprecated. I have improved the LHOST parsing, eliminating the need for this configuration. The update is currently in the development branch and will soon be merged into the main branch.
