### ISSUE TITLE
Villain --- Gets Stuck Updating

### ISSUE THREAD

**Issue by spacezero20** [t3l3machus/Villain#144]
I have to wait for at least 10 minutes every time I run python3 Villain.py for it to check for updates and be ready for use. Why is this? How can I fix it? Can I skip the update check when starting it somehow? 

![villain_updating](https://github.com/t3l3machus/Villain/assets/46658915/bdbd67d5-f6fb-4532-a1a5-3062d6db985e)

**Comment by spacezero20** [comment]
Lately, I've been running it over and over to see if the speeds are changing, however, I'm now running into this port-related issue. I can't even get to the infinite updating phase...take a look and let me know what I can do to resolve this.

![villain_port6501](https://github.com/t3l3machus/Villain/assets/46658915/a4075f9a-b74a-40ca-8b15-9c5bb5bc6f43)

**Comment by t3l3machus** [comment]
You can skip the update with the --skip-update (-s) option:
```
python3 Villain.py -s
```

Also, if you install Villain with apt, there is no update function at all.
Take a look at the help message for more options:
```
python3 Villain.py -h
```

**Comment by spacezero20** [comment]
Okay, I tried downloading it again using the apt method for Kali Linux and I can't find it, so I can't run it. The command python3 Villain.py just doesn't work after installing villain via apt...

It should just be where the rest of my programs are but it isn't. How would I go about finding villain to uninstall and reinstall?

**Comment by spacezero20** [comment]
Just deleted and reinstall via Apt method for Kali Linux, however, I'm not sure where it installed and why it won't run. I can attach a photo fi that would help.

Running the following command: 

sudo python3 Villain.py

**Comment by t3l3machus** [comment]
Now that you installed with apt, just type `villain` in the terminal.
