### ISSUE TITLE
trying to create backdoor generate fails

### ISSUE THREAD

**Issue by leemcchesneyclarkgmailcom** [t3l3machus/Villain#145]
when i type the following:
generate os=windows lhost=wlan0 obfuscate 
i get 
Required argument PAYLOAD not supplied.

**Comment by t3l3machus** [comment]
The syntax has changed, you probably watched a video demonstrating version 1 of the tool. Type `help generate` to see examples of how it works now.

**Comment by leemcchesneyclarkgmailcom** [comment]
thanks
