### ISSUE TITLE
hoaxshell not working.

### ISSUE THREAD

**Issue by anmolganesh07** [t3l3machus/Villain#151]
![InkedVirtualBox_kali-linux-2024 1-virtualbox-amd64_23_05_2024_23_59_41_LI](https://github.com/t3l3machus/Villain/assets/169901871/6abd9d50-a249-4b00-8551-ea0276e9364c)
![Screenshot (8)_LI](https://github.com/t3l3machus/Villain/assets/169901871/63ce626e-09b5-4e19-87b9-a3572a63c66c)
command gets executed but doesnt show any response.

**Comment by t3l3machus** [comment]
Hi, sorry for the delay. Remove the start-process wrapper from the command to see why it errors out. Are you sure the victim host can reach the attacker machine running villain?
