### ISSUE TITLE
Upload command crashes session/tool

### ISSUE THREAD

**Issue by R3d-Developer** [t3l3machus/Villain#157]
Traceback (most recent call last):
  File "/usr/share/villain/Villain.py", line 1534, in <module>
    main()
  File "/usr/share/villain/Villain.py", line 1162, in main
    Hoaxshell.activate_pseudo_shell_session(session_id, os_type)
  File "/usr/share/villain/Core/villain_core.py", line 918, in activate_pseudo_shell_session
    file_path = os.path.expanduser(cmd_list[1])
                                   ~~~~~~~~^^^
IndexError: list index out of range

is what im getting when typing upload not sure why this happens

**Comment by t3l3machus** [comment]
@R3d-Developer this happens because you're omitting the destination path (check `help upload`). The issue has been fixed in the `dev` branch among other things. It will be merged with the `main` branch soon. You can download and use the latest version with:
```
git clone https://github.com/t3l3machus/Villain.git --branch dev
```
