### ISSUE TITLE
Having error : Payload template not found

### ISSUE THREAD

**Issue by Chasecodess** [t3l3machus/Villain#178]
I use the command 
generate payload=windows/reverse_tcp/powershell_reverse_tcp lhost=eth0

and I'm getting an error payload template not found 

And I haven't modified or touched the payload template in the villain folder before ?

How can I solve this error please

**Comment by t3l3machus** [comment]
Hi @Chasecodess, there has been some breaking changes in Villain. The TCP handler was renamed to "reverse TCP" and the string "reverse_tcp" that was part of various template names before, is now stripped. so the template you are looking for is:
```
windows/reverse_tcp/powershell
```

Use tab autocomplete to navigate templates, it will become clearer.

**Comment by t3l3machus** [comment]
* @Chasecodess in case you updated villain and run into this error, you should clone the main branch again and start over, the update may have messed your installation.
