### ISSUE TITLE
Flee function

### ISSUE THREAD

**Issue by cilin1105** [t3l3machus/Villain#186]
Is the "flee" function working? Because every time I try to restart the session I get the message "no active session".am I not logging in correctly?

**Comment by t3l3machus** [comment]
Hi,
I’m having trouble understanding this. When using `flee`, hoaxshell-based agents are not terminated when the program exits. If Villain is restarted, and a hoaxshell agent is still running on the victim, the connection might be re-established. Could you provide more details about this issue and include screenshots if possible?

Thanks!

**Comment by cilin1105** [comment]
I saw that hoaxshell does maintain the connection and not reverse tcp, is there any "help" to explain hoaxshell commands or can you explain to me how to go down to folders and enter folders and perhaps how to execute a python file from hoaxshell. Thanks for this powerful tool.

**Comment by t3l3machus** [comment]
HoaxShell is a pseudo-shell, unfortunately it cannot handle interactive commands e.g., `nano` or any command that opens a new interactive process within a shell session. Consider the following method to execute a command in a specific dir (the screenshot is from a hoaxshell session in villain):

![image](https://github.com/user-attachments/assets/d7a54f5d-7237-4082-adba-f73eba341a8f)

As you can see, it's possible to prefix your command with a directory change and then execute another command. So, to execute a python script that is supposedly located in `/tmp`, you could use the command:
```
cd /tmp && python3 myscript.py
```

Alternatively, you can use full paths to run the hypothetical script from anywhere:
```
python3 /tmp/myscript.py
```

If you'd like to understand how hoaxshell works in general, just grab a generated hoaxshell payload and ask ChatGPT or Copilot to break it down for you.

Cheers

**Comment by cilin1105** [comment]
With hoaxshell the connection persists, it is a bit difficult to manage the shell  but I can poison it again with reverse tcp and be able to work normally. The best tool I have seen in years thanks t3l3machus

**Comment by t3l3machus** [comment]
It still needs a lot of work, but thanks for the support :)
