### ISSUE TITLE
How to Use it with ngrok?

### ISSUE THREAD

**Issue by viralvaghela** [t3l3machus/Villain#19]
can we add features like the  `-ng`  parameter to run over the internet?

**Comment by edikiuspy** [comment]
www.youtube.com/watch?v=ubNUCvFOmwQ

**Comment by t3l3machus** [comment]
@viralvaghela check this out also -> https://github.com/t3l3machus/Villain/issues/17

**Comment by viralvaghela** [comment]
Thanks @t3l3machus @edikiuspy
