### ISSUE TITLE
Crypto package unsafe

### ISSUE THREAD

**Issue by MrurBo** [t3l3machus/Villain#21]
Security tracker:
https://security-tracker.debian.org/tracker/source-package/python-crypto

**Comment by MadHatterENV** [comment]
ah damn, i started a discussion instead of an issue.
Have the same thing using Python3

https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher

**Comment by MrurBo** [comment]
> ah damn, i started a discussion instead of an issue. Have the same thing using Python3
> 
> https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher

That's why I researched the package!

**Comment by t3l3machus** [comment]
Hey thanks for the heads up. Honestly, i find it unlikely for someone to have security issues using this tool based on the recorded CVEs for the crypto module. Gonna have to live with it for a while.
