### ISSUE TITLE
Error during Execution phase

### ISSUE THREAD

**Issue by SkyrusRB** [t3l3machus/Villain#26]
Hello, I am currently having an issue after generating the payload and once I have executed it in the victims machine I get the error. IndexError: list index out of range.
Here is the Screenshot of the error
![Screenshot_20221202_091054](https://user-images.githubusercontent.com/82556556/205192495-dc6db81c-9af0-4d93-85d9-9c3f07574d44.png)

**Comment by abuyusif01** [comment]
Check the pull request i made. this problem is happening cuz for some reasons the server didn't send the username. thats why u got `list index out or range` error

**Comment by SkyrusRB** [comment]
Alright, I'll take a look thank you for your help

**Comment by arm-ARMY** [comment]
I'm having the same issue. But my installation is on a Raspberry Pi 400, Raspberry Pi OS (old Raspbian). Don't know if it is related to my hardware architecture...

**Comment by arm-ARMY** [comment]
Can confirm that is not an issue with arm architecture. I installed it on a fresh Kali installation and get the same error.

**Comment by t3l3machus** [comment]
This issue has been resolved, thanks guys.
