### ISSUE TITLE
No Module named Crypto

### ISSUE THREAD

**Issue by qpxv** [t3l3machus/Villain#34]
How do I fix this error:

![Screenshot_2022-12-06_17-10-24](https://user-images.githubusercontent.com/91433067/205963550-dce0cdb4-5712-48fc-9f02-72c0749745bd.png)

Thanks in Advance!

**Comment by jvgassel** [comment]
Did you installed all requirements? **pip3 install -r requirements.txt**

**Comment by t3l3machus** [comment]
Hey, if you installed the requirements.txt you shouldn't be having issues. Try:
```
pip3 uninstall pycrypto
pip3 install pycryptodome
```
Also make sure you are running this with python3
