### ISSUE TITLE
error crypto

### ISSUE THREAD

**Issue by tchach0** [t3l3machus/Villain#45]
![Screenshot from 2022-12-10 08-41-10](https://user-images.githubusercontent.com/48302465/206872626-55ce18dd-5e25-4e75-ab4f-b98b4e565e6d.png)
![Screenshot from 2022-12-10 08-40-57](https://user-images.githubusercontent.com/48302465/206872628-adb98026-7e86-4bb6-894f-3f0c38acf0de.png)

**Comment by t3l3machus** [comment]
Try installing the requirements as root
