### ISSUE TITLE
connecting to different host problem

### ISSUE THREAD

**Issue by yoap** [t3l3machus/Villain#5]
I tried from my other computer connected to a different internet network. but it doesn't show open session. what should I do?
![image](https://user-images.githubusercontent.com/96961115/202489586-3c03c73d-4515-4a03-9326-03fc59ac4b58.png)
![image](https://user-images.githubusercontent.com/96961115/202489617-cd262575-5b31-490b-a153-aa7d5991acc4.png)

**Comment by t3l3machus** [comment]
If you are trying to establish a session between computers from different LANs, you need to port forward the hoaxshell engine port.
