### ISSUE TITLE
Unable to run the tool. I made sure to install the module. What am I missing?

### ISSUE THREAD

**Issue by Lion3323** [t3l3machus/Villain#51]
sudo python3 Villain.py

Traceback (most recent call last):

  File "/home/lion/Villain/Villain.py", line 11, in <module>

    from Core.common import *

  File "/home/lion/Villain/Core/common.py", line 12, in <module>

    from Crypto.Cipher import AES

ModuleNotFoundError: No module named 'Crypto'

**Comment by Lion3323** [comment]
I've uninstalled and reinstalled all of these several times. Still getting a missing module. Thanks in advance if you get time to help.

sudo python3 Villain.py

Traceback (most recent call last):

  File "/home/lion/Villain/Villain.py", line 11, in <module>

    from Core.common import *

  File "/home/lion/Villain/Core/common.py", line 21, in <module>

    import gnureadline as global_readline

ModuleNotFoundError: No module named 'gnureadline'

**Comment by DeityLink2018** [comment]
Have you tried to install the requirements?

pip3 install -r requirements.txt

Make sure you are in the same directory.

**Comment by Lion3323** [comment]
Yes most certainly did that. I've also uninstalled and tried about three times now. When It says I'm missing something I install it again. I'm stuck on 
ModuleNotFoundError: No module named 'gnureadline'

**Comment by t3l3machus** [comment]
@Lion3323 try installing the requirements with sudo.
