### ISSUE TITLE
Error While running ./Villain.py

### ISSUE THREAD

**Issue by Mr-Hacks** [t3l3machus/Villain#55]
I installed the requirements.txt but when I run the app it gives me this error *ModuleNotFoundError: No module named 'Crypto'*. Please fix it I want to use the tool man.
![vmplayer_F6ca7cgQ5W](https://user-images.githubusercontent.com/72913359/208252385-a3fa1710-cbe5-4bc4-8bfb-51224d6a95a0.png)

I tried to troubleshoot but it didn't work. I tried to install the python *pycrypto* lib but it gives me some kind of installation error.

**Comment by t3l3machus** [comment]
@Mr-Hacks What operating system are you running it on?

**Comment by Mr-Hacks** [comment]
Kali Linux

**Comment by t3l3machus** [comment]
There's nothing to fix, it should be working. The requried module is `pycryptodome`. Try:
```
pip3 uninstall pycrypto
pip3 install pycryptodome
```
if this doesn't solve it try installing the requirements.txt with sudo.

**Comment by Mr-Hacks** [comment]
Thanks, It works now.
