### ISSUE TITLE
How to excute the payload throw cmd

### ISSUE THREAD

**Issue by ithebesha** [t3l3machus/Villain#56]
Hello

its really powerful tool i loved it sooooooooooo much

can you give example if i want to excute the payload throw cmd

for example

CMD> powershell -command " 'payload' "

**Comment by t3l3machus** [comment]
@ithebesha 
1. Generate a Windows payload with Villain.
2. Go to https://www.base64encode.org/, paste the payload, at the "Destination character set" option choose "UTF-16LE" and hit Encode.
3. Copy the base64 output. You can use that in cmd like: `powershell -e <BASE64 OUPUT>`

**Comment by ithebesha** [comment]
@t3l3machus 

i tried the same but its not showing any sessions in villain

**Comment by t3l3machus** [comment]
I'm pretty sure this works, there must be something else going on if you don't see a session. Maybe you tried it with a used payload (the hoaxshell type of payloads are not reusable)? Maybe a mistake with the IP address to connect back? This solution works, try some more, you'll get it.
