### ISSUE TITLE
New feature idea

### ISSUE THREAD

**Issue by aleeessio** [t3l3machus/Villain#60]
Could it be possible to implement also adding meterpreter sessions of phones hacked by apk payload? Or something like that, regarding the possibility to also gain access to phones; hacking computers and smarphones with one tool.

(The script is amazing, thanks man for sharing your knowledge!)

**Comment by t3l3machus** [comment]
@aleeessio Thanks friend, new features are on the way!

**Comment by t3l3machus** [comment]
*Coming back to various issues and PRs I neglected for some time:

This would be great, but Meterpreter requires a specific handler from the Metasploit framework, which I can't implement in Villain. However, I plan to add a feature for migrating sessions to MSF in the future, though it won't be related to Meterpreter.
Nevertheless, thank you for expressing your ideas, hopefully you will keep doing it :)
