### ISSUE TITLE
convert your script into exe( executable) and bypass defender  complete solution is here 

### ISSUE THREAD

**Issue by aksrivastava** [t3l3machus/Villain#67]
### **convert Villian script into  EXE**  -https://youtube.com/shorts/1uxvjBPqu7I?feature=share

**### bypass defender with Villian**- http://youtu.be/EZOW40S_cTM

**Comment by t3l3machus** [comment]
@aksrivastava that's cool and thanks but stop opening issues on my project to advertise yourself. You can post this as a comment to the existing issue about Win defender detection or start a discussion about it.

**Comment by aksrivastava** [comment]
Oh sorry. By mistake, I created the issue. I am contributing from my side. I have to spend a lot of time with that so I am just helping others. Love you, your tool is great
