### ISSUE TITLE
[Feature Request] Release termux version

### ISSUE THREAD

**Issue by Novneetsrivastava** [t3l3machus/Villain#68]
I am trying to install it in termux but is giving erroe please reles termux version also

**Comment by aksrivastava** [comment]
### if you want to install villian on termux you can try these steps:

**First, install termux for GitHub, not playstore**
Then install nethunter on it or follow this video - [](https://youtu.be/62dh0WSaHg4)
after nethunter installation 
now type the following commands

git clone https://github.com/t3l3machus/Villain
cd ./Villain
pip3 install -r requirements.txt
chmod +x Villain
./Villain

**done you have installed villain in your termux**

**Comment by Novneetsrivastava** [comment]
Thank you you have solved my problem I have successfully installed villain in my termux.
