### ISSUE TITLE
VILLAIN + MSFCONSOLE

### ISSUE THREAD

**Issue by UdayA6796** [t3l3machus/Villain#69]
I wanna use villain code and msfconsole I did this but when I do this I do get a session but.... it closes and opens 🤣 kinda hilarious but someone help

**Comment by UdayA6796** [comment]
![Uploading 1673669548135130291599616864376.jpg…]()

**Comment by t3l3machus** [comment]
Unfortunately they are not compatible at the moment. In the near future, I intend to make significant upgrades, improve Villain's payload generation function and add new features :)
