### ISSUE TITLE
Error generating windows payloads with domain argument.

### ISSUE THREAD

**Issue by dchughes2** [t3l3machus/Villain#70]
I get an error when trying to generate a windows payload with domain specified instead of lhost
Villain was started with the command "**sudo python3 Villain.py -c /etc/letsencrypt/live/mydomain.com/fullchain.pem -k /etc/letsencrypt/live/mydomain.com/privkey.pem**"
when i went to generate a payload i use this syntax "**generate os=windows domain=mydomain.com**" i have tried appending www. or removing the .com or even supplying google.com but no matter what is supplied the error message given back is always "**Error parsing arguments. Check your input and try again.**"
I will say that my domain is a bit longer than normal at 28 characters including the .com just in case that contributes to the problem.
Any assistance you can offer is appreciated.

**Comment by t3l3machus** [comment]
@dchughes2 ok, I applied a fix, please update and try again, should work now. Thanks for opening an issue about this.

**Comment by dchughes2** [comment]
Sorry I completely forgot to reply to this months ago but obviously this fixed the issues I had, Thanks for fixing it so quick!

**Comment by t3l3machus** [comment]
@dchughes2 no problem! The update I was talking about is coming this week. The payload generator has been completely redesigned.
