### ISSUE TITLE
Question, not issue

### ISSUE THREAD

**Issue by 0067sdsm** [t3l3machus/Villain#71]
Hi! Great tool, very interesting, so i had a question, is there a way to reuse payloads? Id like to try setting up a ps1 file in the startup or something like that (just playing around) i tryed to check how the code works but i have a smooth brain lol, thanks for any info! :)

**Comment by t3l3machus** [comment]
Hi, the hoaxshell type of payloads generated by the tool are not reusable, but you can use common netcat listener based payloads to catch shells with Villain's netcat multi handler, those are reusable (There's a linked video about how this works in the README). 

I'm going to get back to Villain's development soon and perform a series of major upgrades. The generate payload function will be redesigned completely.

**Comment by 0067sdsm** [comment]
Awsome thank you and good luck, i will be looking forwards to that!
