### ISSUE TITLE
I cannot use the 'exec_outfile="some path"' arguement.

### ISSUE THREAD

**Issue by Venu2HD** [t3l3machus/Villain#74]
This is my commandline:

Villain > generate os=windows lhost=eth0 exec_outfile="C:\Users\\\$env:USERNAME\.local\hack.ps1"
Generating backdoor payload...
Error parsing arguments. Check your input and try again.
Villain > 

What am I doing wrong?
My python version is 3.11.1

**Comment by t3l3machus** [comment]
@Venu2HD nothing wrong, probably a bug. Hang on tight, second major release close to finish, you will definitely have no such issue, the payload generator has been redesigned entirely.
