### ISSUE TITLE
What does the argument -h in Villain.py do?

### ISSUE THREAD

**Issue by DeanRickles** [t3l3machus/Villain#76]
> Villain.py [-h] [-p PORT] [-x HOAX_PORT] [-c CERTFILE] [-k KEYFILE] [-u] [-q]

I've taken a look at the code but for the life of me I cannot work out what -h does for Villain.py, can you please explain for me?

**Comment by t3l3machus** [comment]
Hi, it prints the help message ¯\_(ツ)_/¯

**Comment by DeanRickles** [comment]
I should have known.  ¯\_(ツ)_/¯ 

I haven't used your system yet; I was just reading the documentation and couldn't work out if -h was connected to hoaxshell as you use -H in the arguments...

Thanks for confirming.
