### ISSUE TITLE
pip error while installing

### ISSUE THREAD

**Issue by HackX143** [t3l3machus/Villain#79]
pip3 install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by HackX143** [comment]
please tell me how to solve

**Comment by t3l3machus** [comment]
You can probably solve this by setting up a virtual environment e.g., by using [pyenv](https://github.com/pyenv/pyenv). Check out also this link (there are details if you scroll to the bottom) -> https://github.com/python/cpython/issues/102134
