### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by LucasIsRed** [t3l3machus/Villain#82]
`Traceback (most recent call last):
  File "/home/ubuntu/Villain/Villain.py", line 11, in <module>
    from Core.common import *
  File "/home/ubuntu/Villain/Core/common.py", line 12, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

**Comment by t3l3machus** [comment]
Try installing the requirements as root

**Comment by LucasIsRed** [comment]
> Try installing the requirements as root

genius
