### ISSUE TITLE
Cannot Upload Files to the victim device.

### ISSUE THREAD

**Issue by PH03N1X1000** [t3l3machus/Villain#90]
![image](https://user-images.githubusercontent.com/86946187/232193409-06126af1-3182-4c46-bf2a-67fbec814640.png)
Whenever i try to Upload any file to any location on the victim's Windows it gives this error of Access to path Denied.
I also ran this with Admin PowerShell still the issue persists.

**Comment by t3l3machus** [comment]
@PH03N1X1000 You have to give a name to the file in the destination path (e.g. D:\somefile.ps1)

**Comment by PH03N1X1000** [comment]
Oh extremely sorry for this amateur behaviour. 
I got used to other frameworks too much 
Thanks.

**Comment by t3l3machus** [comment]
No worries, keep playing with it, report any bug you may find :)
