### ISSUE TITLE
IndexError after executing payload 

### ISSUE THREAD

**Issue by blaze0x0** [t3l3machus/Villain#97]
![Screenshot_2023-05-04-09-32-15-008](https://user-images.githubusercontent.com/132434691/236110340-fdfbaa00-dbac-48aa-8813-f3f18297a3ab.jpeg)

Running on TermuxArch
Generate command: generate payload=linux/hoaxshell/sh_curl lhost=wlan0

**Comment by t3l3machus** [comment]
Added a dirty patch for that, thanks!
