### ISSUE TITLE
Proxies?

### ISSUE THREAD

**Issue by 0067sdsm** [t3l3machus/Villain#98]
Its basically just that, if im using the chat function can i use tor and proxychains to stay anon?
Thanks :)

**Comment by 0067sdsm** [comment]
PS im asking bc i didnt really understand how the chat function works.

**Comment by t3l3machus** [comment]
Hey, the chat function will send your message directly to all connected sibling servers. The message is AES encrypted. Unfortunately, I haven't done any proxy experiments with it to be able to give you a verified answer on how to do it atm, but I think that, if you make a TCP connection to send packets (e.g. a message) to a sibling server with an IP that does not much the one that the sibling has in it's sibling servers table (entry created when two siblings are connected), it will drop it. I'm closing this and I'll get back to you in the future

**Comment by 0067sdsm** [comment]
ok thank you
